// Generated by gencpp from file human_navigation/HumanNaviMsg.msg
// DO NOT EDIT!


#ifndef HUMAN_NAVIGATION_MESSAGE_HUMANNAVIMSG_H
#define HUMAN_NAVIGATION_MESSAGE_HUMANNAVIMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace human_navigation
{
template <class ContainerAllocator>
struct HumanNaviMsg_
{
  typedef HumanNaviMsg_<ContainerAllocator> Type;

  HumanNaviMsg_()
    : message()
    , detail()  {
    }
  HumanNaviMsg_(const ContainerAllocator& _alloc)
    : message(_alloc)
    , detail(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _detail_type;
  _detail_type detail;




  typedef boost::shared_ptr< ::human_navigation::HumanNaviMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::human_navigation::HumanNaviMsg_<ContainerAllocator> const> ConstPtr;

}; // struct HumanNaviMsg_

typedef ::human_navigation::HumanNaviMsg_<std::allocator<void> > HumanNaviMsg;

typedef boost::shared_ptr< ::human_navigation::HumanNaviMsg > HumanNaviMsgPtr;
typedef boost::shared_ptr< ::human_navigation::HumanNaviMsg const> HumanNaviMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::human_navigation::HumanNaviMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::human_navigation::HumanNaviMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace human_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'human_navigation': ['/home/emlab/catkin_robocup/src/humannavi_ros/human_navigation/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::human_navigation::HumanNaviMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_navigation::HumanNaviMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::human_navigation::HumanNaviMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::human_navigation::HumanNaviMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_navigation::HumanNaviMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_navigation::HumanNaviMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::human_navigation::HumanNaviMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83c3ad4b113aebdb7a85eba9ba595d50";
  }

  static const char* value(const ::human_navigation::HumanNaviMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83c3ad4b113aebdbULL;
  static const uint64_t static_value2 = 0x7a85eba9ba595d50ULL;
};

template<class ContainerAllocator>
struct DataType< ::human_navigation::HumanNaviMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "human_navigation/HumanNaviMsg";
  }

  static const char* value(const ::human_navigation::HumanNaviMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::human_navigation::HumanNaviMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n\
string detail\n\
";
  }

  static const char* value(const ::human_navigation::HumanNaviMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::human_navigation::HumanNaviMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
      stream.next(m.detail);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HumanNaviMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::human_navigation::HumanNaviMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::human_navigation::HumanNaviMsg_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "detail: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.detail);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUMAN_NAVIGATION_MESSAGE_HUMANNAVIMSG_H
